# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_0.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_0.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold0.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_1.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_1.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold1.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_2.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_2.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold2.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_3.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_3.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold3.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_4.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_4.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold4.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_5.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_5.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold5.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_6.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_6.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold6.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_7.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_7.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold7.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_8.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_8.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold8.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/train_9.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/10days/test_9.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/10days/fold9.xlsx

# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_0.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_0.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold0.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_1.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_1.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold1.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_2.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_2.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold2.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_3.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_3.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold3.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_4.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_4.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold4.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_5.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_5.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold5.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_6.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_6.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold6.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_7.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_7.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold7.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_8.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_8.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold8.xlsx
# python3 lstm.py --train_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/train_9.pickle --test_file /repos/Delivery-Readiness/data/5min_hr_rmssd/30days/test_9.pickle --output_file /repos/Delivery-Readiness/results/5min_hr_rmssd/30days/fold9.xlsx

python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_0.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_0.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold0.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_1.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_1.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold1.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_2.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_2.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold2.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_3.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_3.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold3.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_4.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_4.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold4.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_5.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_5.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold5.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_6.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_6.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold6.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_7.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_7.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold7.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_8.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_8.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold8.xlsx
python3 lstm.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_9.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_9.pickle --output_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/fold9.xlsx
