python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_0.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_0.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold0.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold0.xlsx
python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_1.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_1.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold1.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold1.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_2.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_2.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold2.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold2.xlsx
python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_3.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_3.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold3.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold3.xlsx
python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_4.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_4.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold4.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold4.xlsx
python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_5.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_5.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold5.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold5.xlsx
python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_6.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_6.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold6.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold6.xlsx
python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_7.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_7.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold7.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold7.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_8.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_8.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold8.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold8.xlsx
python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/train_9.pickle --test_file /repos/Delivery-Readiness/data/daily_selected_feature_set_d_readiness/test_9.pickle --output_val_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/val/fold9.xlsx --output_test_file /repos/Delivery-Readiness/results/daily_selected_feature_set_d_readiness/test/fold9.xlsx

# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_0.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_0.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold0.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold0.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_1.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_1.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold1.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold1.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_2.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_2.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold2.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold2.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_3.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_3.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold3.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold3.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_4.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_4.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold4.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold4.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_5.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_5.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold5.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold5.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_6.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_6.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold6.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold6.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_7.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_7.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold7.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold7.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_8.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_8.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold8.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold8.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/train_9.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/10days/test_9.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/val/fold9.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/10days/test/fold9.xlsx

# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_0.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_0.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold0.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold0.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_1.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_1.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold1.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold1.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_2.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_2.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold2.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold2.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_3.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_3.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold3.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold3.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_4.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_4.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold4.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold4.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_5.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_5.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold5.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold5.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_6.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_6.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold6.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold6.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_7.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_7.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold7.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold7.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_8.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_8.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold8.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold8.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/train_9.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/30days/test_9.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/val/fold9.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/30days/test/fold9.xlsx

# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_0.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_0.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold0.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold0.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_1.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_1.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold1.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold1.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_2.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_2.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold2.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold2.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_3.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_3.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold3.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold3.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_4.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_4.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold4.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold4.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_5.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_5.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold5.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold5.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_6.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_6.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold6.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold6.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_7.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_7.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold7.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold7.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_8.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_8.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold8.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold8.xlsx
# python3 lstm_new_split.py --train_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/train_9.pickle --test_file /repos/Delivery-Readiness/data/5min_new_split_non_schedule/largest_window/test_9.pickle --output_val_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/val/fold9.xlsx --output_test_file /repos/Delivery-Readiness/results/5min_new_split_non_schedule/largest_window/test/fold9.xlsx
